Tasks UI
mikekurkin/TaskManager pull request #17
Opened 2022-10-26 15:35 UTC by mikekurkin

2022-10-27 18:33 UTC, greybutton requested changes

2022-10-27 18:33 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        [state]: { cards: concat(boardCards[state].cards, data.items), meta: data.meta },
при обновлении стейта на основе предыдущего лучше использовать prevState

2022-10-27 18:33 UTC, greybutton commented on app/models/task.rb
> +  default_scope { order(updated_at: :desc) }
обычно мы так не делаем)

2022-10-27 18:33 UTC, greybutton commented on config/routes.rb
> +      resources :tasks, only: [:index, :show, :create, :update, :destroy], defaults: { format: 'json' }
формат лучше на все апи добавить, чтобы на каждую отдельно не вешать

2022-10-27 18:33 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
не хватает qs пакета

2022-10-27 18:40 UTC, mikekurkin commented on package.json
> +    "ramda": "^0.28.0",
Ага, не заметил потому что он как чья-то зависимость установился

2022-10-27 18:40 UTC, mikekurkin commented on app/models/task.rb
> +  default_scope { order(updated_at: :desc) }
@greybutton в контроллере лучше упорядочивать?

2022-10-29 19:30 UTC, greybutton commented on app/models/task.rb
> +  default_scope { order(updated_at: :desc) }
в идеале сортировка всегда с фронта приходит в рансаке и на бэке нет кода на нее

2022-10-29 19:31 UTC, greybutton approved these changes
делай плис фиксы отдельными коммитами

2022-10-29 21:02 UTC, mikekurkin commented on app/models/task.rb
> +  default_scope { order(updated_at: :desc) }
@greybutton понял

2022-10-29 21:02 UTC, merged