Devops: Coveralls
mikekurkin/TaskManager pull request #21
Opened 2022-11-01 13:08 UTC by mikekurkin

2022-11-01 20:00 UTC, greybutton requested changes

2022-11-01 20:00 UTC, greybutton commented on .simplecov
> +SimpleCov.start('rails') do
покрытие лучше генерировать только если тесты через CI запущены, иначе всегда будут генерироваться на запуск тестов, а всегда не нужно. Тут я не уверен, что запустится только в CI

и не очень понял зачем выносить в корневой скрытый файл

2022-11-01 20:27 UTC, mikekurkin commented on .simplecov
> +SimpleCov.start('rails') do
@greybutton да, в таком варианте без 'CI' в окружении генерируется html-отчёт simplecov, а с 'CI' — lcov для coveralls. Согласен, избыточно, ща уберу.

Конфиг в корневом файле был бы полезен при использовании нескольких тестовых библиотек. Хоть у нас такого и нет, мне понравилась идея так его отделить.

2022-11-02 05:26 UTC, greybutton approved these changes
> Конфиг в корневом файле был бы полезен при использовании нескольких тестовых библиотек. Хоть у нас такого и нет, мне понравилась идея так его отделить.

ну хоть положи его тогда как руби файл в папку с тестами, больше то нигде этот файл не понадобится. Странно выглядит скрытый файл с руби кодом в корне проекта)

2022-11-03 09:25 UTC, merged